################################################
# Dockerfile to build a new image
################################################
# Base image is ubuntu
FROM ubuntu:16.04
# Author: tranhuyhoang
MAINTAINER tranhuyhoang <hoangth92.nd@gmail.com>
# create 'mynewdir' and 'mynewfile'
RUN mkdir mynewdir
RUN touch /mynewdir/mynewfile
RUN echo 'this is my new container to make image and then push to hub' > /mynewdir/mynewfile
