##################################################################
# Docker file to build a LOG Volume for Apache2 Service
##################################################################
# Base image is Busy box
FROM busybox:latest
# Author hoang
MAINTAINER TranHuyHoang <hoangth92.nd@gmail.com>
# Create a data volume at /var/log/apache2, which is same as log directory PATH set for apache image 
VOLUME /var/log/apache2
# Execute command true
CMD ["/bin/true"]

